FROM node:12-alpine

RUN  mkdir /app
WORKDIR /app

# Install app dependencies
COPY package.json /app

RUN npm install

# Copy the app source
COPY server.js /app
COPY . .

EXPOSE 8080

CMD [ "npm" , "start" ]